version: "3.7"

# Define services
services:
  # App Service
  app:
    image: qr-pesos
    container_name: qr-pesos
    restart: unless-stopped
    ports:
      - "80:8080" # Forward the exposed port 8080 on the container to port 8080 on the host machine